version: '3'

services:
  issue-db:
    image: postgres
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=password
    volumes:
      - /var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - issue-database

  issue-service:
    image: issue-service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - 8081:8081
    volumes:
      - /data/issue-service
    networks:
      - issue-database
      - network

networks:
  issue-database:
    driver: bridge
  network:
    driver: bridge
