openapi: 3.0.3
info:
  title: API Specification for Issue-Service
  description: API Specification for Issue-Service
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/api/issues'
paths:
  /:
    get:
      description: |
        Returns all Issues saved within the issue service
      responses:
        '200':
          description: List of Issues
          content:
            application/json:
              schema:
                type: array
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                type: array
